#!/bin/bash
#Count ansible releases

curl -s http://releases.ansible.com/ansible/ > ansibledoc

VERS="$(cat ansibledoc | grep -oE ansible-[2].[0-9].[0-9].[0].tar.gz | grep -v .*.tar.gz.sha | sort -u | grep -n ansible-2*)"

for SEL in $VERS
do
	echo $SEL
done

echo -n "Select a version: "

read CHOICE

if [ $CHOICE -eq 1 ]
	var1="$( "$SEL" | sed -n "$1"p )"
	then curl -O http://releases.ansible.com/ansible/$var1
fi
