#!/bin/bash
#Count ansible releases

curl -s http://releases.ansible.com/ansible/ > ansibledoc

mv ansibledoc /tmp

printf "Number of versions: "

cat /tmp/ansibledoc | grep -oE 'ansible-[0-9].[0-9].[0-9].tar.gz|ansible-[0-9].[0-9].tar.gz|ansible-[0-9].[0-9].[0-9].[0-9].tar.gz' | grep -v .*.tar.gz.sha | sort -u | wc -l

